### ISSUE TITLE
Shift-TAB does not work

### ISSUE THREAD

**Issue by vjohansen** [segv/jss#3]
I build an emacs 24.3 on centos 6.3

  GNU Emacs 24.3.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.18.9) of 2013-03-11

C-h k S-TAB   reports

<backtab> (translated from <S-iso-lefttab>) is undefined

in jss buffers.

If I go to info mode via C-h i then TAB and S-TAB works fine.

It probably works because info binds backtab. From info.el

```
(define-key map "\e\t" 'Info-prev-reference)
(define-key map [backtab] 'Info-prev-reference)
```

EDIT: github eats < and > 

< backtab > (translated from < S-iso-lefttab >) is undefined

**Comment by segv** [comment]
binding to `<backtab>` should fix the issue (it was bound to `<S-tab>` which, on my machine is `<backtab>`, but on your its not).

let me know if it doesn't solve the problem, and thanks for the bug report!
